### ISSUE TITLE
Game crashes when try to use EssentialGUI tooltip on grass

### ISSUE THREAD

**Issue by Simplebenja** [LambdAurora/LambdaBetterGrass#28]
Whit the tooltip of WTHIT it's all okay
When i look at a grass block with the EssentialGUI tooltip (https://www.curseforge.com/minecraft/mc-mods/essentialgui) activated the game crashes

Mod versión: lambdabettergrass-1.2.1+1.17
Game versión: 1.17.1
EssentialGUI versión: EssentialGUI-1.6.5+1.17.1

[crash-2021-10-27_16.58.57-client.txt](https://github.com/LambdAurora/LambdaBetterGrass/files/7429692/crash-2021-10-27_16.58.57-client.txt)

**Comment by LambdAurora** [comment]
Please report the issue to EssentialGUI (though, I believe this is already done).

The crash report points out it's trying to render a **block model** as an item. The only fix is using another render path.
Trying to render a block model (from the block models manager) as an item should be (and I believe it is) considered bad practice, several mods replace the block model and discard item rendering, since, well, sometimes there's just no way of rendering the model properly, worst being for such mods rendering an overlay it would omit important context (like a blackboard wouldn't render with its drawings, etc.).

But honestly, I'm not really willing to spend more time dealing with a mod hiding its sources making it harder for other mod developers. All the information for the other mod to fix the incompatibility is there though.

**Comment by Simplebenja** [comment]
Thx, yep the bug is also reported to EssentialGUI
