### ISSUE TITLE
Better snow does not retain texture pack of fence.

### ISSUE THREAD

**Issue by RodrigoTR04** [LambdAurora/LambdaBetterGrass#62]
When using the option `Better Snow` some fences get their texture changed to have snow on top, but do not retain their desired texture as per the resource pack. Disabling the option will fix this problem with fences, but will also not connect grass blocks with snow layers on top (which in this case is the desired behavior).

![image](https://user-images.githubusercontent.com/65554156/190234047-98b689ca-8246-44f4-93e2-41e2049128fc.png)

Issue is being opened to either have fences retain their textures and only change the small bits of snow or to add an option that will only connect grass + snow layer blocks and will not change things like fences.

**Comment by LambdAurora** [comment]
This is not a bug: you are using the lambdabettergrass default resource pack which is an extension of the Vanilla resources to include custom fence textures when snowy or mossy.

Disabling said resource pack will fix this issue, the pack isn't made to support other resource packs (which is why it's optional).
