### ISSUE TITLE
Game freeze when starting the game

### ISSUE THREAD

**Issue by Paper-wand** [LambdAurora/LambdaBetterGrass#78]
When I started the game, it froze but didn't crash.
[latest.log](https://github.com/LambdAurora/LambdaBetterGrass/files/11000448/latest.log)

**Comment by LambdAurora** [comment]
Damn it, the **only** platform I can't physically test on doesn't work.
Apologies if no error screen popped up, I blame Mac OS for being weird on this one.

LambdaBetterGrass is a [Quilt](https://quiltmc.org) since 1.19.3. Fabric mods work on Quilt so all you need to do is install Quilt, replace Fabric API with [Quilted Fabric API](https://modrinth.com/mod/qsl) and you should be good.
